import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://growt-farm.vercel.app/');
  await page.getByRole('link', { name: 'Daftar' }).click();
  await page.getByRole('textbox', { name: 'Nama lengkap' }).click();
  await page.getByRole('textbox', { name: 'Nama lengkap' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('M');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('Main ');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('Main S');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('Main Simulation');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('main.simulation@growt.com');
  await page.getByRole('textbox', { name: 'Kata sandi', exact: true }).click();
  await page.getByRole('textbox', { name: 'Kata sandi', exact: true }).fill('password');
  await page.getByRole('textbox', { name: 'Konfirmasi kata sandi' }).click();
  await page.getByRole('textbox', { name: 'Konfirmasi kata sandi' }).fill('password');
  await page.getByRole('button', { name: 'Daftar' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('main.simulation@growt.com');
  await page.getByRole('textbox', { name: 'Kata sandi' }).click();
  await page.getByRole('textbox', { name: 'Kata sandi' }).fill('password');
  await page.getByRole('textbox', { name: 'Kata sandi' }).press('Enter');
  await page.getByRole('button', { name: 'Masuk' }).click();
  await page.goto('https://growt-farm.vercel.app/main/dashboard');
  await page.getByRole('button', { name: 'Registrasi' }).click();
  await page.getByRole('menuitem', { name: 'Perangkat' }).click();
  await page.getByRole('link', { name: 'Buka Pengaturan' }).click();
  await page.getByRole('textbox', { name: 'No. HP' }).click();
  await page.getByRole('textbox', { name: 'No. HP' }).fill('+628123456789');
  await page.getByRole('textbox', { name: 'Tanggal lahir' }).fill('2012-12-12');
  await page.getByRole('combobox', { name: 'Jenis kelamin' }).click();
  await page.getByRole('option', { name: 'Laki-laki' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Simpan perubahan' }).first().click();
  await page.getByRole('combobox', { name: 'Provinsi' }).click();
  await page.getByLabel('DI YOGYAKARTA').getByText('DI YOGYAKARTA').click();
  await page.getByRole('combobox', { name: 'Kab/Kota' }).click();
  await page.getByLabel('KABUPATEN SLEMAN').getByText('KABUPATEN SLEMAN').click();
  await page.getByRole('combobox', { name: 'Kecamatan' }).click();
  await page.getByRole('option', { name: 'MLATI' }).click();
  await page.getByRole('combobox', { name: 'Desa/Kelurahan' }).click();
  await page.getByRole('option', { name: 'SINDUADI' }).click();
  await page.getByRole('combobox', { name: 'Desa/Kelurahan' }).press('CapsLock');
  await page.getByRole('combobox', { name: 'Desa/Kelurahan' }).press('CapsLock');
  await page.getByRole('option', { name: 'SINDUADI' }).press('CapsLock');
  await page.getByRole('option', { name: 'SUMBERADI' }).press('CapsLock');
  await page.locator('html').click();
  await page.getByRole('textbox', { name: 'Jalan' }).click();
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('J');
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('Jl. ');
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('Jl. S');
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('Jl. Sekip ');
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('Jl. Sekip U');
  await page.getByRole('textbox', { name: 'Jalan' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Jalan' }).fill('Jl. Sekip Utara');
  await page.getByRole('textbox', { name: 'Kode pos' }).click();
  await page.getByRole('textbox', { name: 'Kode pos' }).fill('55281');
  await page.getByRole('textbox', { name: 'Detail alamat' }).click();
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('D');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen ');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen I');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu ');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu K');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu Komputer dan ');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu Komputer dan E');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu Komputer dan Elektronika ');
  await page.getByRole('textbox', { name: 'Detail alamat' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Detail alamat' }).fill('Departemen Ilmu Komputer dan Elektronika, FMIPA UGM');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Simpan perubahan' }).nth(1).click();
  await page.getByRole('button', { name: 'Registrasi' }).click();
  await page.getByRole('menuitem', { name: 'Perangkat' }).click();
  await page.getByRole('textbox', { name: 'Nomor serial *' }).click();
  await page.getByRole('textbox', { name: 'Nomor serial *' }).fill('SN-1234');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).click();
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).fill('T');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).fill('Timbangan ');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).fill('Timbangan K');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).fill('Timbangan Kandang ');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama perangkat *' }).fill('Timbangan Kandang UGM');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Registrasikan perangkat' }).click();
  await page.getByRole('link', { name: 'Perangkat' }).click();
  await page.getByRole('main').getByRole('button', { name: 'Toggle Sidebar' }).click();
  await page.getByRole('button', { name: 'Registrasi' }).click();
  await page.getByRole('menuitem', { name: 'Ternak' }).click();
  await page.getByRole('textbox', { name: 'RFID *' }).click();
  await page.getByRole('textbox', { name: 'RFID *' }).fill('RF123456');
  await page.getByRole('textbox', { name: 'Nama *' }).click();
  await page.getByRole('textbox', { name: 'Nama *' }).fill('D');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('Domba ');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('Domba G');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('Domba Gunung');
  await page.getByRole('textbox', { name: 'Nama *' }).click();
  await page.getByRole('textbox', { name: 'Nama *' }).fill('');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('J');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John ');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John D');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John Doe');
  await page.getByRole('textbox', { name: 'Ras *' }).click();
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('E');
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('');
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('G');
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('Garut');
  await page.getByRole('link', { name: 'Beranda' }).click();
  await page.getByRole('link', { name: 'Masuk', exact: true }).click();
  await page.getByRole('button', { name: 'Registrasi' }).click();
  await page.getByRole('menuitem', { name: 'Perangkat' }).click();
  await page.getByRole('button', { name: 'Registrasi', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Ternak' }).click();
  await page.getByRole('textbox', { name: 'RFID *' }).click();
  await page.getByRole('textbox', { name: 'RFID *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'RFID *' }).fill('RF123456');
  await page.getByRole('textbox', { name: 'Nama *' }).click();
  await page.getByRole('textbox', { name: 'Nama *' }).fill('J');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John ');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John D');
  await page.getByRole('textbox', { name: 'Nama *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nama *' }).fill('John Doe');
  await page.getByRole('textbox', { name: 'Ras *' }).click();
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('G');
  await page.getByRole('textbox', { name: 'Ras *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Ras *' }).fill('Garut');
  await page.getByRole('textbox', { name: 'Tanggal lahir *' }).fill('2012-12-12');
  await page.getByRole('combobox', { name: 'Jenis *' }).click();
  await page.getByRole('option', { name: 'Sheep' }).click();
  await page.getByRole('combobox', { name: 'Kelamin *' }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
});